version: '3.4'

services:

  nginx: 
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "8080:80"
    depends_on: 
      - service1
      - service2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  service1:
    image: istio_demo/service1:v1
    build:
      context: .
      dockerfile: ../services/service1/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Service2Uri=http://service2:5000
      - Service3Uri=http://service3:5000
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  service2:
    image: istio_demo/service2:v1
    build:
      context: .
      dockerfile: ../services/Service2/Dockerfile
    ports:
      - 5001:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      
  service3:
    image: istio_demo/service3:v1
    build:
      context: .
      dockerfile: ../services/Service3/Dockerfile
    ports:
      - 5002:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  
  rabbitmq:
    