apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: rabbitmq-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: rabbitmq-demo.com
      http:
        paths:
        - path: /subscriber/(.*)
          pathType: Prefix
          backend:
            service:
              name: subscriber
              port:
                number: 80
        - path: /publisher/(.*)
          pathType: Prefix
          backend:
            service:
              name: publisher
              port:
                number: 80
