version: '3.4'

services:

  nginx: 
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "80:80"
    depends_on: 
      - publisher
      - subscriber
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  publisher:
    image: rabbitmq_demo/publisher:v1
    build:
      context: ../../
      dockerfile: services/Publisher/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file: 
      - ./rabbitmq.env
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  subscriber:
    image: rabbitmq_demo/subscriber:v1
    build:
      context: ../../
      dockerfile: services/Subscriber/Dockerfile
    ports:
      - 5001:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file: 
      - ./rabbitmq.env
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest        